name: Photon
options:
  bundleIdPrefix: com.ciamac
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    DEVELOPMENT_TEAM: "3AUT8DTWP3"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "2"

targets:
  Photon:
    type: application
    platform: iOS
    sources:
      - path: Photon
        excludes:
          - "Info.plist"
          - "Pieces"
      - path: Photon/Pieces
        type: folder
        buildPhase: resources
    info:
      path: Photon/Info.plist
      properties:
        CFBundleDisplayName: Illusions
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Dark
        UIStatusBarHidden: true
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ciamac.illusions
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
