// Photon shorts engine.
//
// One layout, one beat runner, one end card, N pieces. A piece is an entry in
// shorts.config.json plus a draw function in draws/<slug>.js. Adding a short is
// writing a draw function and four lines of copy; it is not authoring a page.
//
// This exists because v1 hand-wrote each short as its own standalone page, and
// the three pieces drifted apart from each other within a single session (three
// different figure centres, three end-card positions, type landing on the
// spiral). The layout can no longer regress because there is only one of it.
//
//   node engine/short.mjs            build every enabled piece
//   node engine/short.mjs cafe-wall  build one
//
// Output: build/<slug>.html, a self-contained deterministic page exposing
// window.SHORT {fps, frames} and window.seek(frame), which capture.mjs and
// verify_layout.mjs both drive.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');

// ---------------------------------------------------------------- layout law
// Held identical across every piece. Changing a number here changes the whole
// series, which is the point.
export const LAYOUT = {
  W: 1080, H: 1920,
  CEIL: 470,     // header band bottom; no header text may cross it
  FLOOR: 1450,   // foot band top; the countdown lives below it
  CY: 960,       // stimulus centre, midpoint of 470..1450
  MEASURE: 920,  // text measure (1080 minus 80px padding each side)
};

const PALETTE = {
  dark:  { field: '#0c0b09', strong: '#e8e0d0', dim: 'rgba(232,224,208,0.55)', faint: 'rgba(232,224,208,0.40)' },
  light: { field: '#8d8579', strong: '#0c0b09', dim: 'rgba(12,11,9,0.52)',     faint: 'rgba(12,11,9,0.42)' },
};

// ------------------------------------------------------------------ template
function page(cfg, drawSrc) {
  const pal = PALETTE[cfg.mode];
  const field = cfg.field || pal.field;
  const fps = cfg.fps || 30;
  const frames = Math.round(cfg.dur * fps);

  // The veil is always the FIELD colour, never ink. On the afterimage a dark end
  // card would wipe the percept the viewer is still holding; the neutral field
  // has to persist under the closing type. Applied uniformly so the set matches.
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${cfg.piece} · Photon short</title>
<style>
  /* GENERATED by engine/short.mjs from shorts.config.json. Do not hand-edit.
     Band law: HEADER 0..${LAYOUT.CEIL} | STIMULUS ${LAYOUT.CEIL}..${LAYOUT.FLOOR} (cy=${LAYOUT.CY}) | FOOT ${LAYOUT.FLOOR}.. */
  *{margin:0;padding:0;box-sizing:border-box}
  html,body{width:${LAYOUT.W}px;height:${LAYOUT.H}px;overflow:hidden;background:${field}}
  body{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
  canvas{position:fixed;inset:0}
  .t{position:fixed;left:0;width:${LAYOUT.W}px;text-align:center;pointer-events:none}
  #plate{position:fixed;left:0;top:0;width:${LAYOUT.W}px;height:580px;
    background:linear-gradient(${field} 58%, transparent 100%);opacity:${cfg.plate ? 0.92 : 0}}
  #chapter{top:100px;font-family:"SF Mono",ui-monospace,Menlo,monospace;font-size:24px;
    letter-spacing:0.30em;text-transform:uppercase;color:${pal.faint}}
  #piece{top:142px;font-family:"SF Mono",ui-monospace,Menlo,monospace;font-size:20px;
    letter-spacing:0.18em;text-transform:uppercase;color:${pal.faint}}
  #line{top:236px;font-size:62px;font-weight:300;letter-spacing:0.01em;color:${pal.strong};
    padding:0 80px;line-height:1.24}
  #sub{top:402px;font-size:32px;font-weight:300;color:${pal.dim}}
  #count{top:1548px;font-family:"SF Mono",ui-monospace,Menlo,monospace;font-size:30px;
    letter-spacing:0.10em;color:${pal.dim}}
  #veil{position:fixed;inset:0;background:${field}}
  #close1{top:800px;font-size:52px;font-weight:300;color:${pal.strong};padding:0 90px;line-height:1.35}
  #close2{top:1030px;font-family:"SF Mono",ui-monospace,Menlo,monospace;font-size:24px;
    letter-spacing:0.26em;text-transform:uppercase;color:${pal.faint}}
  #close3{top:1090px;font-family:"SF Mono",ui-monospace,Menlo,monospace;font-size:28px;
    letter-spacing:0.10em;color:${pal.strong}}
</style>
</head>
<body>
<canvas id="c" width="${LAYOUT.W}" height="${LAYOUT.H}"></canvas>
<div id="plate"></div>
<div class="t" id="chapter">Photon to Phenomenology</div>
<div class="t" id="piece">${cfg.piece}</div>
<div class="t" id="line"></div>
<div class="t" id="sub"></div>
<div class="t" id="count"></div>
<div id="veil"></div>
<div class="t" id="close1">${cfg.close || 'Vision is not recording,<br>it is construction.'}</div>
<div class="t" id="close2">Photon to Phenomenology</div>
<div class="t" id="close3">ciamac.com</div>
<script>
"use strict";
const CFG = ${JSON.stringify({ ...cfg, fps, frames }, null, 2)};
const L = ${JSON.stringify(LAYOUT)};
const FPS = ${fps};
window.SHORT = { fps: FPS, frames: ${frames} };

const ctx = document.getElementById('c').getContext('2d');
const el = id => document.getElementById(id);

function fadeIn(t, a, d) { return d <= 0 ? (t >= a ? 1 : 0) : Math.max(0, Math.min(1, (t - a) / d)); }
function lerp(a, b, u) { return a + (b - a) * u; }
function ease(u) { return u < 0.5 ? 2*u*u : 1 - Math.pow(-2*u + 2, 2) / 2; }

// The sweep is the reveal: one scalar the draw function reads as C.p, running
// from its "from" value to its "to" value across "dur", starting at "at". For
// the lifted interactive pieces this is exactly the parameter the viewer used
// to drag (cafe wall row offset, Ebbinghaus surround contrast, Ponzo
// convergence), so the short shows the same proof the page does, on rails.
function sweepAt(t) {
  const s = CFG.sweep;
  if (!s) return 1;
  const u = ease(Math.max(0, Math.min(1, (t - s.at) / (s.dur || 1))));
  return lerp(s.from, s.to, u);
}

// Beats: the last beat at or before t that defines a field wins, and fades in
// from that beat's own time. Pass "" to clear a field.
function beatFor(t, key) {
  let best = null;
  for (const b of CFG.beats) {
    if (b.t <= t && b[key] !== undefined) best = b;
  }
  return best;
}
function runText(t, endFade) {
  for (const key of ['line', 'sub']) {
    const b = beatFor(t, key);
    const e = el(key);
    if (!b || b[key] === '') { e.textContent = ''; e.style.opacity = 0; continue; }
    e.textContent = b[key];
    e.style.opacity = fadeIn(t, b.t, b.fade === undefined ? 0.6 : b.fade) * (1 - endFade);
  }
  const c = CFG.countdown, ce = el('count');
  if (c && t < c.until) {
    ce.textContent = String(Math.ceil(c.until - t));
    ce.style.opacity = fadeIn(t, c.from || 1.2, 0.5) * (1 - endFade);
  } else { ce.textContent = ''; ce.style.opacity = 0; }
}

${drawSrc}

window.seek = function (f) {
  const t = f / FPS;
  const C = {
    t, p: sweepAt(t),
    W: L.W, H: L.H, cx: L.W / 2, cy: L.CY,
    field: ${JSON.stringify(field)},
    ink: '#0c0b09', cream: '#e8e0d0',
    cfg: CFG, lerp, fadeIn, ease,
  };
  ctx.fillStyle = C.field; ctx.fillRect(0, 0, L.W, L.H);
  draw(ctx, t, C);

  const endFade = fadeIn(t, CFG.end, CFG.endFade || 1.1);
  runText(t, endFade);
  el('plate').style.opacity = ${cfg.plate ? 0.92 : 0} * (1 - endFade);
  el('veil').style.opacity = endFade * 0.94;
  for (const id of ['close1', 'close2', 'close3']) el(id).style.opacity = endFade;
};
window.seek(0);
</script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------- main
const config = JSON.parse(readFileSync(resolve(ROOT, 'shorts.config.json'), 'utf8'));
const only = process.argv.slice(2);
const outDir = resolve(ROOT, 'build');
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

let n = 0;
for (const cfg of config.pieces) {
  if (cfg.enabled === false) continue;
  if (only.length && !only.includes(cfg.slug)) continue;
  const drawPath = resolve(ROOT, 'draws', `${cfg.slug}.js`);
  if (!existsSync(drawPath)) { console.error(`MISSING draw: draws/${cfg.slug}.js`); process.exitCode = 1; continue; }
  const html = page(cfg, readFileSync(drawPath, 'utf8'));
  writeFileSync(resolve(outDir, `${cfg.slug}.html`), html);
  console.log(`built build/${cfg.slug}.html  ${cfg.dur}s  ${Math.round(cfg.dur * (cfg.fps || 30))} frames`);
  n++;
}
console.log(`\n${n} page(s) built`);
